#!/usr/bin/env python3
"""Analyze the font atlas to show band structure and per-glyph widths."""
from PIL import Image

img = Image.open('textures/font/roboto.png').convert('RGBA')
W, H = img.size
px = img.load()
print(f'Atlas size: {W}x{H}')

def row_has_alpha(y):
    return any(px[x, y][3] > 10 for x in range(W))

def col_range_has_alpha(x, y0, y1):
    return any(px[x, y][3] > 10 for y in range(y0, y1))

bands = []
in_band = False
band_y0 = 0
for y in range(H):
    has = row_has_alpha(y)
    if has and not in_band:
        in_band = True; band_y0 = y
    elif not has and in_band:
        in_band = False; bands.append((band_y0, y))
if in_band:
    bands.append((band_y0, H))

all_glyphs = []
for (ys, ye) in bands:
    col_has = [col_range_has_alpha(x, ys, ye) for x in range(W)]
    in_g = False; gx0 = 0; band_g = []
    for x, has in enumerate(col_has):
        if has and not in_g:
            in_g = True; gx0 = x
        elif not has and in_g:
            in_g = False; band_g.append((gx0, ys, x, ye))
    if in_g:
        band_g.append((gx0, ys, W, ye))
    all_glyphs.extend(band_g)
    print(f'Band y={ys:3d}..{ye:3d}  h={ye-ys:2d}: {len(band_g):2d} glyphs  widths={[g[2]-g[0] for g in band_g]}')

print(f'\nTotal: {len(all_glyphs)} glyphs')

# Show glyph->codepoint assignment as generated by the current script
print('\nCurrent sequential assignment (slot = glyph index, cp = slot+32):')
FIRST_CP = 33  # '!'
for i, (x0, y0, x1, y1) in enumerate(all_glyphs):
    cp = FIRST_CP + i
    if cp > 126:
        print(f'  glyph {i}: NO CODEPOINT (would be cp={cp})')
        continue
    w = x1 - x0
    expected_cp = FIRST_CP + i
    print(f'  glyph {i:2d} at x={x0:3d}..{x1:3d} w={w:2d}  -> assigned cp={expected_cp} "{chr(expected_cp)}"')
