#!/usr/bin/env python3
"""gen_font_data.py – generate a bitmap font atlas from Roboto-Regular.ttf.

Loads font/Roboto-Regular.ttf and renders ASCII 32-126 glyphs in strict
codepoint order into an RGBA atlas (white glyph on transparent background).
The alpha channel carries glyph coverage; the text shader samples .a directly.

Outputs:
    textures/font/roboto.png       – RGBA bitmap atlas
    src/render/shaders/roboto_atlas.h  – UV data + cap_height constant
"""

import pathlib
from PIL import Image, ImageDraw, ImageFont


FONT_PATH  = pathlib.Path(__file__).parent.parent / 'font' / 'Roboto-Regular.ttf'
ATLAS_PATH = pathlib.Path(__file__).parent.parent / 'textures' / 'font' / 'roboto.png'
OUT_PATH   = (pathlib.Path(__file__).parent.parent
              / 'src' / 'render' / 'shaders' / 'roboto_atlas.h')

FONT_SIZE   = 32   # render size in pixels
PAD         = 2    # padding around each glyph cell (pixels)
FIRST_CP    = 33   # '!'
LAST_CP     = 126  # '~'
TOTAL_SLOTS = 95   # indices 0..94  →  codepoints 32..126
ATLAS_W     = 512  # atlas width (power of two)


def next_pow2(n: int) -> int:
    p = 1
    while p < n:
        p <<= 1
    return p


def main() -> None:
    font = ImageFont.truetype(str(FONT_PATH), FONT_SIZE)

    # ── Collect per-glyph metrics ──────────────────────────────────────────
    # getbbox() returns (left, top, right, bottom) relative to draw origin.
    glyph_meta = []   # (char, bbox, advance_px)
    for cp in range(FIRST_CP, LAST_CP + 1):
        ch   = chr(cp)
        bbox = font.getbbox(ch)          # may return None for invisible chars
        adv  = font.getlength(ch)
        if bbox is None or bbox[2] <= bbox[0] or bbox[3] <= bbox[1]:
            bbox = (0, 0, 1, 1)          # give it a 1×1 placeholder
        glyph_meta.append((ch, bbox, adv))

    # ── Compute row height: tallest glyph + 2×PAD ─────────────────────────
    row_h = max(b[3] - b[1] for (_, b, _) in glyph_meta) + 2 * PAD

    # ── Pack glyphs left-to-right, wrapping into rows ──────────────────────
    rows: list[tuple[int, list]] = []   # (row_y, [(cell_x, glyph_meta), ...])
    cur_row: list = []
    cur_x  = PAD
    row_y  = PAD

    for info in glyph_meta:
        _, bbox, _ = info
        cell_w = (bbox[2] - bbox[0]) + 2 * PAD
        if cur_x + cell_w > ATLAS_W and cur_row:
            rows.append((row_y, cur_row))
            row_y += row_h
            cur_row = []
            cur_x   = PAD
        cur_row.append((cur_x, info))
        cur_x += cell_w

    if cur_row:
        rows.append((row_y, cur_row))
        row_y += row_h

    ATLAS_H = next_pow2(row_y + PAD)

    # ── Render atlas ──────────────────────────────────────────────────────
    atlas = Image.new('RGBA', (ATLAS_W, ATLAS_H), (0, 0, 0, 0))
    draw  = ImageDraw.Draw(atlas)

    # slot data: index = cp - 32
    # tuple: (u0, v0, u1, v1, advance_uv, bearing_y)
    EMPTY = (0.0, 0.0, 0.0, 0.0, 0.0, 0.0)
    slots = [EMPTY] * TOTAL_SLOTS

    # Space (slot 0) – not rendered, just measure
    space_adv = font.getlength(' ')
    slots[0]  = (0.0, 0.0, 0.0, 0.0, space_adv / ATLAS_W, 0.0)

    for (ry, row) in rows:
        for (cell_x, (ch, bbox, adv)) in row:
            gw = bbox[2] - bbox[0]
            gh = bbox[3] - bbox[1]

            # Position the draw call so the glyph's ink lands in the cell.
            # PIL draws text at (x, y) where (x, y) is the top-left of the
            # bounding box when using the default 'lt' anchor.
            x_draw = cell_x + PAD - bbox[0]
            y_draw = ry      + PAD - bbox[1]
            draw.text((x_draw, y_draw), ch, font=font,
                      fill=(255, 255, 255, 255))

            u0 = (cell_x + PAD)      / ATLAS_W
            v0 = (ry      + PAD)     / ATLAS_H
            u1 = (cell_x + PAD + gw) / ATLAS_W
            v1 = (ry      + PAD + gh) / ATLAS_H
            # bearing_y: pixels from draw-origin down to top of ink at render size
            bearing_y = float(bbox[1])
            slots[ord(ch) - 32] = (u0, v0, u1, v1, adv / ATLAS_W, bearing_y)

    ATLAS_PATH.parent.mkdir(parents=True, exist_ok=True)
    atlas.save(str(ATLAS_PATH))
    print(f'Written {ATLAS_PATH}  ({ATLAS_W}x{ATLAS_H})')

    # ── Write C++ header ──────────────────────────────────────────────────
    # Cap-height = pixel height of 'H'
    h_bbox  = font.getbbox('H')
    cap_h   = float(h_bbox[3] - h_bbox[1]) if h_bbox else float(FONT_SIZE)

    lines = [
        '#pragma once',
        '// AUTO-GENERATED by tools/gen_font_data.py -- DO NOT EDIT',
        '#include <cstddef>',
        '',
        f'// Roboto bitmap atlas: {ATLAS_W}x{ATLAS_H} pixels, rendered at {FONT_SIZE}px.',
        f'// Glyph slots cover ASCII 32 (space) through {31 + TOTAL_SLOTS}.',
        '// Index  =  codepoint - 32.',
        '',
        '// Per-glyph UV bounds, advance, and vertical bearing.',
        'struct RoboGlyph {',
        '    float u0, v0, u1, v1;  // atlas UV [0,1]',
        '    float advance_uv;       // advance = advance_uv * atlas_w * scale',
        '    float bearing_y;        // px from draw-origin to ink-top at render size',
        '};',
        '',
        f'static constexpr int   k_roboto_atlas_w    = {ATLAS_W};',
        f'static constexpr int   k_roboto_atlas_h    = {ATLAS_H};',
        '// Pixel height of the cap-height (H glyph at render size).',
        '// Used to convert font_size (pixels) to a glyph scale factor.',
        f'static constexpr float k_roboto_cap_height = {cap_h:.1f}f;',
        '',
        'static const RoboGlyph k_roboto_glyphs[95] = {',
    ]

    for i, (u0, v0, u1, v1, adv, by) in enumerate(slots):
        cp  = i + 32
        ch  = chr(cp)
        cmt = repr(ch) if ch != '\\' else "'\\\\'  "
        lines.append(
            f'    {{ {u0:.6f}f, {v0:.6f}f, {u1:.6f}f, {v1:.6f}f, {adv:.6f}f, {by:.1f}f }},  // {cmt}'
        )

    lines += ['};', '']

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text('\n'.join(lines))
    print(f'Written {OUT_PATH}  (cap_height={cap_h:.1f}px, atlas {ATLAS_W}x{ATLAS_H})')


if __name__ == '__main__':
    main()
